apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      name: my-pod
      labels:
        app: example
    spec:
      containers:
      - name: my-con
        image: 891377344729.dkr.ecr.ap-south-1.amazonaws.com/example-app
        ports:
        - containerPort: 3000
